### ISSUE TITLE
Blinds accessories not working

### ISSUE THREAD

**Issue by acresp** [Sinclair81/LOGO-HomeKit-Bridge#3]
Hello

Nice to have the bridge.cfg OTA upload avalaible, it seems to work as expected with great informations.
I have an issue with the blind accessories.
There is no blind working, and resulting in a "No Response" state when I try to use them.

I'm using your UDF v1 (because I use the homebridge-logo-ts, as the bridge is not totally ready)
I tried the UDF v2 but I have an issue on the Homebridge plugin: the "push" on tile is working perfectly with this version, but unfortunately there is a "state" issue with the homebridge plugin: the state is not correctly read between the UDFv2/homebridge-logo-ts plugin. 

Kind regards

**Comment by acresp** [comment]
Hallelujah, I found an Arduino usb2serial in a drawer 🙂 

So here is the debug when I try to activate a blind:

<img width="816" alt="Screen Shot 2021-09-26 at 15 00 54" src="https://user-images.githubusercontent.com/57019575/134809145-a74faa17-a8f5-4afc-a52f-47d992c23e26.png">

And it causes the Bridge to reboot after the watchdog timer not reset. I think this is related to the other Issue I opened, I tried to enable blind, but the bridge freeze and become unresponsive, so the other accessories don't work anymore after that.

<img width="550" alt="Screen Shot 2021-09-26 at 15 03 42" src="https://user-images.githubusercontent.com/57019575/134809248-8ac90012-626a-476d-b29a-d04c2b46a2eb.png">

**Comment by Sinclair81** [comment]
Yes Blind v1 and Logo-HomeKit-Bridge do not go together. Just like Blind v2 and Homebridge-Logo-TS plugin don't go together. I'll take another look at the UDFs, maybe they'll make more compatibility there. So that you can use both bridges.

**Comment by acresp** [comment]
Mmmhhh.. Tried with the LHB & Blind UDF v2 and same issue.
Here is the serial output

<img width="819" alt="Screen Shot 2021-09-26 at 16 22 02" src="https://user-images.githubusercontent.com/57019575/134811866-240522aa-2be8-4f27-9379-0bc05d313e4a.png">

Here is the LOGO program (with udf blind v2)
<img width="685" alt="Screen Shot 2021-09-26 at 16 23 02" src="https://user-images.githubusercontent.com/57019575/134811879-8ded5067-29a2-4abb-90da-60d953a09185.png">

And here is the json setup

```
            {
               "name":"Volet Bureau",
               "type":"blind",
               "blindConvertValue":1,
               "blindSetTargetPos":"VW30",
               "blindGetTargetPos":"VW30",
               "blindGetPos":"VW32",
               "blindGetState":"VW34"
            },
```

**Comment by Sinclair81** [comment]
I was able to reproduce the error!
I will fix it asap.
Blind v2 and Homebridge-Logo-TS work together, if it is controlled analogue it works without any problems!

**Comment by acresp** [comment]
> I was able to reproduce the error!
> I will fix it asap.
> Blind v2 and Homebridge-Logo-TS work together, if it is controlled analogue it works without any problems!

Nice!
Yes about the blind v2 and homebridge-logo-TS I was able to make it work for the control. But it seems that for the "state" there is something weird. If I use the digital input to control the blind, the state is not corrected with the homebridge plugin.

**Comment by Sinclair81** [comment]
Oh yes that doesn't work anymore! I have '"updateInterval": 60000,' everywhere and it no longer works.

**Comment by Sinclair81** [comment]
I think everything is working again now!

**Comment by acresp** [comment]
> I think everything is working again now!

Yes, no more crash!! 🙂 
So I tried with one blind and the udf v2, is it normal that if I use the digital input to open or close, there is no percentage value in the Home app ? Only a "Open" state, even if the blind is only 50% opened. With the Homebridge plugin and the UDF v1 the state was perfectly reflected.

**Comment by Sinclair81** [comment]
No, thats not normal! But yesterday I also noticed that at the Homebridge. So it could be that I did something wrong in UDF Blind v2. Is it still possible with v1? Or can you look in the web server / on the display of the logo what comes out of the UDF (B336 and B337 from the program above, for example)?

**Comment by acresp** [comment]
I put some AM to monitor the output.
With the Blind v1, If I use the digital input to open/close, I have a value at the output (see AM1)
<img width="441" alt="Screen Shot 2021-09-27 at 17 43 53" src="https://user-images.githubusercontent.com/57019575/134941421-007cf33b-5469-40c9-aaf2-bfa740ac8e2b.png">

But with the Blind v2, If I use the digital input to open/close, AM1 stays at 0.
<img width="516" alt="Screen Shot 2021-09-27 at 17 41 50" src="https://user-images.githubusercontent.com/57019575/134941506-03c3cdcd-788b-43e4-83cf-7d9c6deeec75.png">

**Comment by Sinclair81** [comment]
Thanks for looking! I saw exactly the same thing.
I had to revise the blind UDF a bit and you have to adjust the config of the bridge
-> blindGetTargetPos == blindGetPos (as described in the readme).

**Comment by acresp** [comment]
It seems ok!
And also in the Homebridge plugin, you confirm ?

**Comment by Sinclair81** [comment]
Yes! It works again with the Homebridge too!
